services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: multivate
      POSTGRES_PASSWORD: multivate
      POSTGRES_DB: multivate
    ports:
      - "5432:5432"
    volumes:
      - multivate_pg:/var/lib/postgresql/data
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - multivate_redis:/data

volumes:
  multivate_pg:
  multivate_redis:
